### ISSUE TITLE
add deplural methods?

### ISSUE THREAD

**Issue by jiming** [atteo/evo-inflector#14] opened 2017-11-29 06:09 UTC
What do you say? Is it easy to do?

Thanks!

**Comment by sentinelt** [comment] 2017-11-29 11:49
I based the pluralization algorithm on [Damian Conway's paper](http://users.monash.edu/~damian/papers/HTML/Plurals.html). But I'm not aware of any papers for depluralization.
That said the naive approach would be to revert all the rules for singularization. This will probably have low accuracy. So the next step would be to test those inverted rules with the data from Wiktionary and optionally adjust them.

I don't have the time to dig into this currently. I will accept contributions though.

**Comment by jiming** [comment] 2017-11-29 12:04
Thank you!

**Comment by sentinelt** [comment] 2018-05-16 23:42
Duplicate of #8

**Closed by sentinelt** 2018-05-16 23:42 UTC
